### ISSUE TITLE
Use @vue/cli to build a webpack-devServer based on android device: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by lgd8981289** [framework7io/framework7#2822]
基于 `@vue/cli `来构建的项目，当我执行 `npm run serve` 的时候运行在 `android 5.0`的设备上，出现了 `“Unexpected strict mode reserved word”` 的错误，我观察错误的原因发现是因为 `template7`、`dom7`、`framework7` 中使用了 `ES6` 的语法.。我尝试使用 `babel` 来去处理这个问题，但是很快出现了更多的错误，比如： `object is not a function （framework7.esm.bundle.js）`。这个问题应该如何解决，使运行时不再出现 `ES6` 的语法。我的英语不好，我已经尽力表达了，希望你能明白。

The project built based on `@vue/cli `, when I executed `npm run serve` on the device of `android 5.0`, there was an error of `Unexpected strict mode reserved word`, I observed the error. The reason is because the syntax of `ES6` is used in `template7`, `dom7`, `framework7`. I tried to use `babel` to handle this problem, but there were more errors soon, such as: `object is not a function (framework7.esm.bundle.js)`. How should this problem be solved so that the syntax of `ES6` no longer appears at runtime. My English is not good, I have tried my best to express it, I hope you can understand.

**Comment by lgd8981289** [comment]
就在刚刚我运行官方提供的 [framework7-template-vue-webpack](https://github.com/framework7io/framework7-template-vue-webpack) 到 `android5.0` 的设备上，出现了 `Uncaught TypeError: undefined is not a function` 的错误在 `accordion-content.js:9` 中。


Just after I ran the officially provided [framework7-template-vue-webpack](https://github.com/framework7io/framework7-template-vue-webpack) to the `android5.0` device, `Uncaught appeared. The error of TypeError: undefined is not a function` is in `accordion-content.js:9`.

**Comment by victor1342** [comment]
I encountered this same issue after updating to the latest version of framework7-template-vue-webpack. Prior to updating, my project worked perfectly in Android 5.1. The quick fix is to use a version from earlier this year, before the heavy changes to the build settings were made. The "long fix" is to look over exactly what has changed in the build settings.
