### ISSUE TITLE
Error when creating popover in Vue component (F7 core)

### ISSUE THREAD

**Issue by Toverbal** [framework7io/framework7#3955]
* Framework7 version: 6.3.8
* Platform and Target: All
* Live Link or JSFiddle: https://f7issue.tagpulse.nl/
* See attachment for simple example:
[popover-vue-component-issue.zip](https://github.com/framework7io/framework7/files/7503299/popover-vue-component-issue.zip)

### Describe the bug
When migrating our app from v5 to v6 we encountered a very strange issue. Our setup is core Framework7, but we use Vue (2) for rendering parts of our pages. When, however, we create a popover in a Vue component, a strange javascript error is thrown.

```
vue.js:1906 
        
TypeError: getters[getterKey] is not a function
    at getGetterValue (create-store.js:23)
    at getterValue (create-store.js:70)
    at Object.get (create-store.js:123)
    at observe (vue.js:994)
    at defineReactive$$1 (vue.js:1035)
    at Observer.walk (vue.js:947)
    at new Observer (vue.js:935)
    at observe (vue.js:1003)
    at defineReactive$$1 (vue.js:1035)
    at Observer.walk (vue.js:947)
```

This results in the popover not working. The error is thrown when executing app.popover.create. However, subsequent calls to app.popover.create actually do work. It only throws the error in a Vue component. When you create a popover in a Vue instance, it doesn't throw the error. Also in F7 v5 it does not throw this error, it's F7 v6 specific.

When I finally isolated the problem I've created a new empty F7 app in which the problem is demonstrated. Starting the app and clicking on the bars icon will throw the error. Clicking on the bars icon again will not throw the error and open the popover as expected.

The code to create and open the popup is as follows:

```
            const element = $(this.$el).find('.context-menu-popover')[0];
            const actionsButton = $(this.$el).find('.context-menu-button')[0];

            **this.contextMenuPopover = window.app.popover.create({
                el: element,
                targetEl: actionsButton,
            });**
            this.contextMenuPopover.open();
```

This code can be found in the component (test-component.js). The ** marked statement throws the error.

### To Reproduce
1. Extract the demo app in the attachment
2. Run it on a simple webserver (don't open index.html from the hard drive, because the on pageAfterInit event will not fire)
3. Click on the bars icon and the error will appear in the console
4. Click on the bars icon again and there will be no error and the popover will open

### Screenshots
Screenshot 1: error after clicking once
![image](https://user-images.githubusercontent.com/964136/140892149-7da216cc-aea2-413a-9ddd-eef8cda9fe33.png)

Screenshot 2: no error after clicking twice
![image](https://user-images.githubusercontent.com/964136/140892301-c1e03a9c-60b0-4f2d-83e7-02cb0e324306.png)

**Comment by nolimits4web** [comment]
> Vue (2)

Framework7 v6 compatible only with Vue.js v3

**Comment by Toverbal** [comment]
Okay, that explains a lot! I thought Vue 3 was only mandatory when using Framework7 Vue and not with Framework7 core. Shouldn't Framework7 core have no depedencies on Vue? My assumption was that core means that you can use any other library without clashing.

**Comment by nolimits4web** [comment]
Core version should work there. Then it would be better to see live CodeSandbox/JSFiddle with the issue

**Comment by Toverbal** [comment]
I'm not sure if I can fiddle it, but there is a live example (with the issue) on https://f7issue.tagpulse.nl/
I also attached the sample project when I wrote the initial post.

**Comment by Toverbal** [comment]
Hi, I've tried my sample project with Vue 3 in stead of Vue 2 and now the error does not occur, so it definitely has something to do with Vue, but still I am convinced that this should not occur when using Framework7 **Core** in combination with Vue 2. Could you share your thoughts on this?
