### ISSUE TITLE
Cannot find module 'framework7-react' in V7

### ISSUE THREAD

**Issue by CyrusNG** [framework7io/framework7#4010]
* Framework7 version: 7.0.1
* React.js version: 16.14.0
* Webpack version: 4.46.0

### Describe the bug
Cannot find module 'framework7-react' when run program with webpack after I upgrade V6 to V7.

### To Reproduce
1. Upgrade V6 to V7 (V6 works...)
2. Run:`webpack-dev-server --host 0.0.0.0 --mode development --config config/webpack.base.config.js --hot --history-api-fallback`

### Expected behavior
It should run program success.

### Actual Behavior
ERROR: Module not found: Error: Can't resolve 'framework7-react' in xxxxx

### Try to solved
I Compare V6 and V7's package.json, then update framework7-react's package.json file as below, then solved:
  ```
"description": "Build full featured iOS & Android apps using Framework7 & React",
  "main": "framework7-react.js",       # add this line
  "module": "framework7-react.js",     # add this line
  "exports": {
    ".": "./framework7-react.js",
    "./components/*": "./components/*"
  },
```

FINALLY I am not sure whether my update is correct, but works in my webpack environment, And I am NOT sure whether this issue is common, but I hope it can be solved in coming version. Many thanks.

**Comment by nolimits4web** [comment]
https://github.com/framework7io/framework7/issues/4012
