### ISSUE TITLE
F7 react v6.0.1 typescript support problem 

### ISSUE THREAD

**Issue by rwsbillyang** [framework7io/framework7#3800]
* Framework7 version: "^6.0.1",
* React.js version:  "^17.0.1",

Same config,  no problem when use F7 react 5.x, but after upgrade to v6.0.1, lots of errors are reported:

### Describe the bug
1. Report lots of errors like the following when compile :
```
     TS2322: Type '{ children: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.

[tsl] ERROR in .../f7tmp/node_modules/framework7-react/components/pie-chart/pie-chart.d.ts(13,41)
      TS1005: ';' expected.
[tsl] ERROR in .../f7tmp/node_modules/framework7-react/components/pie-chart/pie-chart.d.ts(13,115)
      TS1131: Property or signature expected.
ERROR in .../f7tmp/node_modules/framework7-react/components/list-input/list-input.d.ts(79,23)
      TS1109: Expression expected.
```
2. 
After add toast config:
```js
  // Framework7 Parameters
  const f7params = {
    name: 'My App', // App name
      theme: 'auto', // Automatic theme detection

      toast: {
        closeTimeout: 1000,
        closeButton: false,
        position: 'center',
        horizontalPosition:'center'
      },

      // App store
      store: store,
      // App routes
      routes: routes,

  };
```

`<App { ...f7params } >` reports error: 
```
      TS2322: Type '{ children: Element[]; name: string; theme: string; store: StoreObject; routes: ({ path: string; component: (props: any) => Element; async?: undefined; } | { path: string; async: ({ router, to, resolve }: { ...; }) => void; component?: undefined; })[]; toast: { ...; }; }' is not assignable to type 'AppProps'.
  The types of 'toast.position' are incompatible between these types.
    Type 'string' is not assignable to type '"center" | "top" | "bottom" | undefined'.
```

3. Button  onClick reports error:
```js
    <Button onClick={()=>console.log("clicked")}>test Click</Button>
```

```
 TS2322: Type '{ children: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
```

### To Reproduce
 use `framework7 create --skipUpdate` to create a default web app, then add typescript support as following:
```
npm install --save-dev @types/react @types/react-dom typescript ts-loader source-map-loader
```

build/ webpack.config.js
```patch
     hotUpdateMainFilename: 'hot/hot-update.json',
   },
   resolve: {
-    extensions: ['.js', '.jsx', '.json'],
+    extensions: ['.tsx', '.ts', '.js', '.jsx', '.json'],
     alias: {
 
       '@': resolvePath('src'),
@@ -73,7 +74,8 @@ module.exports = {
         ],
       },
 
-
+      // All files with a '.ts' or '.tsx' extension.
+      { test: /\.tsx?$/, loader: "ts-loader" },
 
       {
         test: /\.css$/,
```

build/build.js
```patch
diff --git a/build/build.js b/build/build.js
index 8a8cfa5..0414543 100644
--- a/build/build.js
+++ b/build/build.js
@@ -21,7 +21,7 @@ rm(isCordova ? './cordova/www' : './www/', (removeErr) => {
     process.stdout.write(`${stats.toString({
       colors: true,
       modules: false,
-      children: false, // If you are using ts-loader, setting this to true will make TypeScript erro
rs show up during build.
+      children: true, // If you are using ts-loader, setting this to true will make TypeScript error
s show up during build.
       chunks: false,
       chunkModules: false,
     })}\n\n`);
```

**Comment by nolimits4web** [comment]
Will be fixed in next update. As for f7params they should be typed:
```
import { Framework7Parameters } from 'framework7/types';

... 

const f7params: Framework7Parameters = {
  ...
}
```
